# In Repository Root (Yoga folder)

workflows:
  ios-free-test:
    name: iOS Free Test Build (Try 8 - Explicit FLUTTER_ROOT)
    working_directory: yoga-app # Points to your Flutter project folder
    max_build_duration: 60

    environment:
      flutter: stable 
      xcode: latest 
      groups:
        # Apple ID credentials group
        - apple_developer_credentials 
        # Removed firebase_secrets group as you don't have the plist file
        
    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter pub get
          flutter gen-l10n # Correct localization command

      # Combined step to set FLUTTER_ROOT and run pod install
      - name: Install Pods (Native iOS dependencies)
        script: |
          echo "Explicitly setting FLUTTER_ROOT before pod install..."
          # Force set FLUTTER_ROOT using Codemagic's built-in variable
          export FLUTTER_ROOT=$CM_FLUTTER_ROOT 
          # Now run pod install
          pod install
        working_directory: ios # Run this script inside the 'ios' folder
        
      - name: Build IPA for testing
        script: |
          flutter build ipa --release \
            --export-method development \
            --build-name=1.0.0 \
            --build-number=$(($BUILD_NUMBER + 1))
            
    artifacts:
      # Save the final signed IPA file
      - $CM_BUILD_DIR/**/build/ios/ipa/*.ipa
      # Save Xcode build logs
      - $CM_BUILD_DIR/ios/build/logs/build.log 
      - /tmp/xcodebuild*.log 

    publishing:
      email:
        recipients:
          - pguptaapple@icloud.com