// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWQJequeld6bnSFZFxgYrtSNA2E72La7Q',
    appId: '1:402747381975:web:656bb50181bc8a0ef3f892',
    messagingSenderId: '402747381975',
    projectId: 'yogaapp-fd2c7',
    authDomain: 'yogaapp-fd2c7.firebaseapp.com',
    storageBucket: 'yogaapp-fd2c7.firebasestorage.app',
    measurementId: 'G-YLXDSKHPMK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMogPfuJxPxtZQubs2MJtlOelSAXz1JEM',
    appId: '1:402747381975:android:656bb50181bc8a0ef3f892',
    messagingSenderId: '402747381975',
    projectId: 'yogaapp-fd2c7',
    storageBucket: 'yogaapp-fd2c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6ISKLJ-mw0enEz02Nu4AyEyZE4eyJZ8M',
    appId: '1:402747381975:ios:38a8c0738900d2a2f3f892',
    messagingSenderId: '402747381975',
    projectId: 'yogaapp-fd2c7',
    storageBucket: 'yogaapp-fd2c7.firebasestorage.app',
    iosBundleId: 'com.example.yogaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6ISKLJ-mw0enEz02Nu4AyEyZE4eyJZ8M',
    appId: '1:402747381975:ios:38a8c0738900d2a2f3f892',
    messagingSenderId: '402747381975',
    projectId: 'yogaapp-fd2c7',
    storageBucket: 'yogaapp-fd2c7.firebasestorage.app',
    iosBundleId: 'com.example.yogaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWQJequeld6bnSFZFxgYrtSNA2E72La7Q',
    appId: '1:402747381975:web:0df6804d82c21e5bf3f892',
    messagingSenderId: '402747381975',
    projectId: 'yogaapp-fd2c7',
    authDomain: 'yogaapp-fd2c7.firebaseapp.com',
    storageBucket: 'yogaapp-fd2c7.firebasestorage.app',
    measurementId: 'G-6N6CL1SDV1',
  );
}
